const testData = {
  "Hematology": [
    { name: "Hemoglobin", normal: "13.5–17.5 g/dL", unit: "g/dL" },
    { name: "WBC Count", normal: "4,000–11,000 /µL", unit: "/µL" },
    { name: "Platelet Count", normal: "150,000–450,000 /µL", unit: "/µL" },
    { name: "RBC Count", normal: "4.7–6.1 million/µL", unit: "million/µL" },
    { name: "Hematocrit", normal: "38.8–50%", unit: "%" },
    { name: "MCV", normal: "80–100 fL", unit: "fL" },
    { name: "MCH", normal: "27–33 pg", unit: "pg" },
    { name: "MCHC", normal: "33.4–35.5 g/dL", unit: "g/dL" },
    { name: "RDW", normal: "11.5–14.5%", unit: "%" },
    { name: "ESR", normal: "0–22 mm/hr", unit: "mm/hr" },
    { name: "Reticulocyte Count", normal: "0.5–1.5%", unit: "%" },
    { name: "Differential Count", normal: "Varies", unit: "-" },
    { name: "Neutrophils", normal: "40–60%", unit: "%" },
    { name: "Lymphocytes", normal: "20–40%", unit: "%" },
    { name: "Monocytes", normal: "2–8%", unit: "%" },
    { name: "Eosinophils", normal: "1–4%", unit: "%" },
    { name: "Basophils", normal: "0.5–1%", unit: "%" },
    { name: "BT", normal: "1–6 minutes", unit: "minutes" },
    { name: "CT", normal: "8–15 minutes", unit: "minutes" },
    { name: "MP", normal: "Negative", unit: "-" },
    { name: "PT", normal: "11–13.5 seconds", unit: "seconds" },
    { name: "APTT", normal: "30–40 seconds", unit: "seconds" },
    { name: "INR", normal: "0.8–1.1", unit: "-" },
    { name: "D-Dimer", normal: "< 0.5 µg/mL", unit: "µg/mL" },
    { name: "Fibrinogen", normal: "200–400 mg/dL", unit: "mg/dL" },
    { name: "LE Cells", normal: "Negative", unit: "-" },
    { name: "Sickling Test", normal: "Negative", unit: "-" },
    { name: "G6PD", normal: "7–20 U/g Hb", unit: "U/g Hb" },
    { name: "Peripheral Smear", normal: "Normal", unit: "-" },
    { name: "Bone Marrow", normal: "Normal", unit: "-" }
  ],
  "Serology": [
    { name: "HCV", normal: "Non-Reactive", unit: "-" },
    { name: "HBsAg", normal: "Negative", unit: "-" },
    { name: "HIV", normal: "Negative", unit: "-" },
    { name: "Widal Test", normal: "<1:80", unit: "-" },
    { name: "RA Factor", normal: "<14 IU/mL", unit: "IU/mL" },
    { name: "ASO Titre", normal: "<200 IU/mL", unit: "IU/mL" },
    { name: "CRP", normal: "<10 mg/L", unit: "mg/L" },
    { name: "TPHA", normal: "Negative", unit: "-" },
    { name: "RPR", normal: "Non-Reactive", unit: "-" },
    { name: "Dengue IgG/IgM", normal: "Negative", unit: "-" },
    { name: "Typhidot", normal: "Negative", unit: "-" },
    { name: "ANA", normal: "Negative", unit: "-" },
    { name: "Anti-dsDNA", normal: "Negative", unit: "-" },
    { name: "CMV IgG/IgM", normal: "Negative", unit: "-" },
    { name: "EBV IgG/IgM", normal: "Negative", unit: "-" },
    { name: "Brucella", normal: "<1:160", unit: "-" },
    { name: "Leptospira", normal: "Negative", unit: "-" },
    { name: "Toxoplasma IgG", normal: "Negative", unit: "-" },
    { name: "Rubella IgG", normal: "Positive", unit: "-" },
    { name: "Syphilis", normal: "Negative", unit: "-" },
    { name: "Anti-CCP", normal: "<20 U/mL", unit: "U/mL" },
    { name: "COVID-19 IgG", normal: "Negative", unit: "-" },
    { name: "COVID-19 IgM", normal: "Negative", unit: "-" },
    { name: "HBcAb", normal: "Negative", unit: "-" },
    { name: "HBeAg", normal: "Negative", unit: "-" },
    { name: "Anti-HAV", normal: "Negative", unit: "-" },
    { name: "Anti-HEV", normal: "Negative", unit: "-" },
    { name: "Anti-HBs", normal: "Positive", unit: "-" },
    { name: "RF Latex", normal: "Negative", unit: "-" },
    { name: "Toxoplasma IgM", normal: "Negative", unit: "-" }
  ],
  "Histopathology": [
    { name: "Liver Biopsy", normal: "No Pathology", unit: "-" },
    { name: "Skin Biopsy", normal: "No Malignancy", unit: "-" },
    { name: "Gastric Biopsy", normal: "Normal", unit: "-" },
    { name: "Endometrial Biopsy", normal: "Proliferative Phase", unit: "-" },
    { name: "Renal Biopsy", normal: "Normal", unit: "-" },
    { name: "Breast Biopsy", normal: "No Cancer", unit: "-" },
    { name: "Colon Biopsy", normal: "Normal Mucosa", unit: "-" },
    { name: "Thyroid Biopsy", normal: "Benign", unit: "-" },
    { name: "Prostate Biopsy", normal: "BPH", unit: "-" },
    { name: "Lung Biopsy", normal: "No Tumor", unit: "-" },
    { name: "Bone Marrow Biopsy", normal: "Normal", unit: "-" },
    { name: "Lymph Node Biopsy", normal: "Reactive", unit: "-" },
    { name: "Cervical Biopsy", normal: "No Dysplasia", unit: "-" },
    { name: "Muscle Biopsy", normal: "Normal", unit: "-" },
    { name: "Placental Biopsy", normal: "Normal", unit: "-" },
    { name: "Skin Punch Biopsy", normal: "No Pathology", unit: "-" },
    { name: "Nasal Polyp", normal: "Inflammatory", unit: "-" },
    { name: "Oral Biopsy", normal: "No Malignancy", unit: "-" },
    { name: "Testicular Biopsy", normal: "Normal", unit: "-" },
    { name: "Esophageal Biopsy", normal: "Normal", unit: "-" },
    { name: "Bladder Biopsy", normal: "No Tumor", unit: "-" },
    { name: "Rectal Biopsy", normal: "Normal", unit: "-" },
    { name: "Ovarian Biopsy", normal: "Benign", unit: "-" },
    { name: "Uterine Biopsy", normal: "Proliferative", unit: "-" },
    { name: "Tongue Biopsy", normal: "Normal", unit: "-" },
    { name: "Larynx Biopsy", normal: "Normal", unit: "-" },
    { name: "Scalp Biopsy", normal: "Normal", unit: "-" },
    { name: "Pancreas Biopsy", normal: "No Tumor", unit: "-" },
    { name: "Spinal Biopsy", normal: "Normal", unit: "-" },
    { name: "Adrenal Biopsy", normal: "Normal", unit: "-" }
  ],
  // Similarly, define "Microbiology", "Biochemistry", "Culture Tests", "Special Chemistry", etc...
};
